# Generated by Django 3.0.2 on 2020-06-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='id_top_answer',
            field=models.IntegerField(default=-1, verbose_name='id лучшего ответа'),
        ),
    ]
